# This is the standard conda configuration file. Use this file to list
# the conda packages that you need installed in your environment.
channels:
  - conda-forge

dependencies:
  - jupyter_contrib_nbextensions==0.5.1
  # Required until https://github.com/jupyterhub/repo2docker/pull/1196 is merged
  - jupyterhub-singleuser>=3.0,<4.0
  # Set default python version to 3.10 - repo2docker sets it to 3.7 instead by default,
  # which can limit us to older package versions
  - python=3.10
  # Everyone wants to use nbgitpuller for everything, so let's do that
  - nbgitpuller=1.1.*
  # Add other packages here:
  - numpy
  - matplotlib
  - scipy
  - pandas
  - tqdm
  - s3fs
  - awscli
  - scikit-learn
  - datalad
  - datalad-container
  - singularity
  - altair
  - seaborn
  - graphviz
  - pygraphviz
  - python-graphviz
  - jax
  - numba
  - cython
  - pytorch==2.3.1
  - torchvision==0.18
  - pytorch::cpuonly
  - dcm2niix
  - openneuro-py
  - ipyvolume
  - nodejs
  - s5cmd
  - imbalanced-learn
  - tensorflow
  - nitime
  - statsmodels
  - openneuro-py
  - pip:
    - best-toolbox
    - nbgitpuller
    - pymef
    - pybids
    - nipype
    - neuropythy>=0.12.15
    - dipy
    - mne
    - nilearn
    - dask[complete]
    - nimare
    - osfclient
    - line_profiler
    - memory_profiler
    - black
    - mne_bids
    - ipympl
    - pyfftw
    - pliers
    - duecredit
    - git-credential-helpers
    - cloudpathlib[s3,gz,azure]
    - colorspacious
    - requests
    - platformdirs
    - git+https://github.com/rmarkello/abagen.git@dc4a007
    - afqinsight
    - ieegprep
    - jupyter-keepalive