#! /bin/bash

set -ex

# Make a link from the shared documents directory to the user home directory.
ln -s ~/shared/docs ~/docs

jupyter labextension install ipyvolume
jupyter labextension install jupyter-threejs
